const REPLACED_ITEM_REG_EXP: RegExp = /\?\((.+?)\)/gi;
const REPLACED_ARRAY_OF_OBJECTS_REG_EXP: RegExp = /\?\[(.+?)]/gi;
const REPLACED_ARRAY_OF_OBJECTS_NAME_REG_EXP: RegExp = /\?{(.+?)}/gi;
const REPLACED_LIST_OF_PARAMS_REG_EXP: RegExp = /\?IN\[(.+?)]/gi;
const REPLACED_LIST_OF_PARAMS_NAME_REG_EXP: RegExp = /\?{(.+?)}/gi;
const REPLACED_STRING_WITHOUT_QUOTES_REG_EXP: RegExp = /\?onlyString\((.+?)\)/gi;

export {
    REPLACED_ITEM_REG_EXP,
    REPLACED_ARRAY_OF_OBJECTS_REG_EXP,
    REPLACED_ARRAY_OF_OBJECTS_NAME_REG_EXP,
    REPLACED_LIST_OF_PARAMS_REG_EXP,
    REPLACED_LIST_OF_PARAMS_NAME_REG_EXP,
    REPLACED_STRING_WITHOUT_QUOTES_REG_EXP
};